### ISSUE TITLE
Wrong media limits for A4 paper using HP OfficeJet 7740 Pro due ignoring duplicated sizes in ppdCacheCreateWithPPD()

### ISSUE THREAD

**Issue by piratenpanda** [OpenPrinting/libppd#29]
**Describe the bug**
When printing A4 pages with the printer a wrong media size is used. See https://bugs.launchpad.net/ubuntu/+source/cups/+bug/2040270 for more details. I have the same issue on arch

**To Reproduce**
Print A4 pages with the HP OfficeJet 7740 Pro. 
Media has wrong offset as the printer thinks the paper has media limits of: 0.42 x 0.42 to 27.52 x 35.14 cm

**Expected behavior**
Print normal A4 pages

**System Information:**
 - OS and its version: latest Arch Linux, above linked bug is on Ubuntu 23.04
 - Application: Evince 45 and Firefox tested
 - CUPS version 2.4.7

**Comment by michaelrsweet** [comment]
Yeah I'm not sure what they are trying to do but it isn't right, even for regular PPDs. Both use the same commands and the cupsInteger0 value (26) is the PCL media size value for A4... Probably the right fix is to exclude any sizes that use a non-standard name for a standard size.

**Comment by zdohnal** [comment]
Thinking about it deeper - what if the HPLIP (or any other) filter does depend on using non-standard size name? In such cases we might need to keep all the sizes, even the duplicate ones... WDYT? @tillkamppeter @michaelrsweet

**Comment by zdohnal** [comment]
In case my idea is not useful, I've created PR for Mike's suggestion - use always standard name if the size is standardized.

**Comment by tillkamppeter** [comment]
Letting `ppd-cache.c` keep duplicate sizes would preserve the non-standard names which some sizes got in addition, but is it conforming with IPP standards to have duplicate page sizes in the list?

We can also have:
1. Non-duplicate paper sizes with non-standard name
2. The default page size's name is non-standard, as the only incarnation of that size has a non-standard name, or the incarnation with non-standard name is selected as default
3. All incarnations of a given size have non-standard names

By replacing all entries of each page size by one entry with standard name **and** changing the default page sizes name to the standard nameof the size referenced by it should solve all the above problems.

Only if the driver needs the non-standard names one needs to somehow preserve them, for example by keeping the duplicate sizes ...

**Comment by Pivert** [comment]
Hi,

Finally, I have a solution. For now, it was easier to remove the line in the ppd file. Here is the diff:

```
# diff /etc/cups/ppd/OfficeJet_Pro_7740.ppd.O /etc/cups/ppd/OfficeJet_Pro_7740.ppd
2c2
< *%%%% PPD file for HP Officejet Pro 7740 Series with CUPS.
---
> *%%%% PPD file for HP Officejet Pro 7740 Series with CUPS. (Pivert Edit)
279d278
< *PageSize IndexCardA4/Index Card A4 8.27x11.69in : "<</cupsInteger0 26/PageSize[595.44 841.68]/ImagingBBox null>>setpagedevice"
```

Thanks for the tip !
